### ISSUE TITLE
pip Not Install: mlimages/gather/imagenet/imagenet_api.py

### ISSUE THREAD

**Issue by yoshida-mediba** [icoxfog417/mlimages#6]
1. pip install mlimages

```
iSysdev11:tmp yoshida$ pip install mlimages
Collecting mlimages
  Using cached mlimages-0.5.zip
Requirement already satisfied: requests in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from mlimages)
Requirement already satisfied: aiohttp in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from mlimages)
Requirement already satisfied: chardet in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from aiohttp->mlimages)
Requirement already satisfied: multidict>=2.0 in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from aiohttp->mlimages)
Requirement already satisfied: async_timeout>=1.1.0 in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from aiohttp->mlimages)
Requirement already satisfied: yarl>=0.5.0 in /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from aiohttp->mlimages)
Installing collected packages: mlimages
  Running setup.py install for mlimages ... done
Successfully installed mlimages-0.5
```

2. Run

```
iSysdev11:tmp yoshida$ python test.sh  -imagenet --wnid n02121808
Traceback (most recent call last):
  File "test.sh", line 6, in <module>
    cmd.main(args)
  File "/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages/scripts/gather_command.py", line 25, in main
    from mlimages.gather.imagenet import ImagenetAPI
ImportError: No module named 'mlimages.gather.imagenet'
```

3. Not Installed: mlimages/gather/imagenet/imagenet_api.py

```
iSysdev11:tmp yoshida$ find /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages/
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages/
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__init__.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__pycache__
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__pycache__/__init__.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__pycache__/label.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__pycache__/model.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//__pycache__/training.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//gather
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//gather/__init__.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//gather/__pycache__
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//gather/__pycache__/__init__.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//label.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//model.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/__init__.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/__pycache__
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/__pycache__/__init__.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/__pycache__/gather_command.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/__pycache__/label_command.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/gather_command.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//scripts/label_command.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//training.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/__init__.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/__pycache__
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/__pycache__/__init__.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/__pycache__/file_api.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/__pycache__/log_api.cpython-35.pyc
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/file_api.py
/Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages//util/log_api.py
```

**Comment by yoshida-mediba** [comment]
4. Fix

```
iSysdev11:tmp yoshida$ cp -r mlimages-0.5/mlimages/gather/imagenet /Users/yoshida/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mlimages/gather/
```
